config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#top"
  get "/home/special_thanks", to: "home#special_thanks", as: "special_thanks"
  get "/home/terms", to: "home#terms", as: "terms"
  get "/home/privacy_policy", to: "home#privacy_policy", as: "privacy_policy"

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete "/sign_out", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
    resources :another_website_links, only: [:create, :update, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  resources :todos do
    resource :like, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_default_todos
  has_many :todos, dependent: :destroy
  has_many :likes
  has_many :liked_todos, through: :likes, source: :todo
  has_many :another_website_links, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def liked?(todo)
    likes.exists?(todo_id: todo.id)
  end

  def like(todo)
    likes.create(todo_id: todo.id)
  end

  def unlike(todo)
    likes.find_by(todo_id: todo.id).destroy
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def level
    self.todos.where(checked: true).count
  end

  def categories_progress
    todos.default_todos.order(id: :asc).group_by(&:category).transform_values do |todos|
      checked = todos.count(&:checked)
      total = todos.size
      (checked.to_f / total * 100).round
    end
  end

  def self.find_or_create_from_auth(auth)
    user = self.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |user_record|
      user_record.nickname = auth[:info][:nickname]
      user_record.name = auth[:info][:name]
      user_record.image = auth[:info][:image].gsub("_normal", "")
    end

    user.assign_attributes(
      nickname: auth[:info][:nickname],
      name: auth[:info][:name],
      image: auth[:info][:image].gsub("_normal", "")
    )

    user.save if user.changed?
    user
  end

  private

  def create_default_todos
    DEFAULT_TODOS.each do |category, descriptions|
      descriptions.each do |description|
        todos.create!(category: category, description: description, default: true)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(level: :desc).page(params[:page]).per(15)
  end

  def show
    @default_todos_grouped = @user.todos.default_todos.order(id: :asc).group_by(&:category)
    @categories_progress = @user.categories_progress
    # @user_todos_grouped = @user.todos.user_todos.order(id: :desc).group_by(&:category)
    @following_users = @user.following
    @follower_users = @user.followers
  end

  def edit
  end

  def destroy
    @user.destroy
    reset_session
    redirect_to root_path, status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def progress_bar_color(index)
    case index
    when 0
      "bg-primary"
    when 1
      "bg-success"
    when 2
      "bg-info"
    when 3
      "bg-warning"
    when 4
      "bg-danger"
    else
      "bg-secondary"
    end
  end
end

app/views/users/_follow_form.html.erb
<% if current_user == user %>
  <button type="button" class="btn btn-primary disabled"> <%= t("users.show.follow") %></button>
<% elsif current_user %>
  <div id="follow_form" class="mb-3">
    <% if current_user.following?(user) %>
      <%= form_with(model: current_user.active_relationships.find_by(followed: user), html: { method: :delete }) do |f| %>
        <div><%= hidden_field_tag :redirect_to, request.fullpath %></div>
        <%= f.submit t("users.show.unfollow"), class: "btn btn-secondary" %>
      <% end %>
    <% elsif current_user != user %>
      <%= form_with(model: current_user.active_relationships.build) do |f| %>
        <div><%= hidden_field_tag :redirect_to, request.fullpath %></div>
        <div><%= hidden_field_tag :followed_id, user.id %></div>
        <%= f.submit t("users.show.follow"), class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_modal.html.erb
<a href="#" class="link-primary mx-2" data-bs-toggle="modal" data-bs-target="#<%= modal_id %>">
  <p><%= title %>: <%= count %></p>
</a>
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_id %>Label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="<%= modal_id %>Label"><%= title %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% if users.present? %>
          <ul class="list-group">
            <% users.each do |user| %>
              <li class="list-group-item">
                <%= link_to user_path(user) do %>
                  <%= image_tag user.image, alt: user.name, size: "50x50" %>
                  <%= user.name %>
                <% end %>
                <%= render "follow_form", user: user %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p><%= t("users.show.nolists") %></p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_rendering_modal.html.erb
<div class="d-flex justify-content-center">
  <%= render 'modal', modal_id: 'followedModal', title: t("users.show.following"), count: @user.following.count, users: @following_users %>
  <%= render 'modal', modal_id: 'followerModal', title: t("users.show.followers"), count: @user.followers.count, users: @follower_users %>
</div>

app/views/users/_todo.html.erb
<div class="todos my-5">
  <div id="flash" class="my-3">
    <%= render "shared/flash" %>
  </div>

  <ul class="nav nav-pills nav-fill bg-light" id="categoryTabs" role="tablist">
    <% DEFAULT_TODOS.keys.each_with_index do |category, index| %>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if index == 0 %>" id="<%= "#{category}-tab" %>" data-bs-toggle="tab" href="#<%= category %>" role="tab" aria-controls="<%= category %>" aria-selected="<%= 'true' if index == 0 %>">
          <%= category %>
        </a>
      </li>
    <% end %>
  </ul>
  <div class="tab-content" id="categoryTabDescripitions">
    <% @default_todos_grouped.each_with_index do |(category, todos), index| %>
      <div class="tab-pane fade <%= 'show active' if index == 0 %>" id="<%= category %>" role="tabpanel" aria-labelledby="<%= "#{category}-tab" %>">
        <ul class="list-group">
          <% todos.each_with_index do |todo, index| %>
            <li class="list-group-item">
              <%= form_with(model: todo, method: :patch, local: true) do |form| %>
                Level: <%= index + 1 %>
                <%= form.check_box :checked, class: "form-check-input me-1", onchange: 'this.form.requestSubmit(); triggerPartyEffect(this);', id: "todo_checked_#{todo.id}" %>
                <%= form.label :checked, todo.description, class: "form-check-label stretched-link", for: "todo_checked_#{todo.id}" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="d-grid gap-2">
      <%= link_to t("users.show.link_button") , todos_path, class: "btn btn-primary mt-3", method: :get %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="white-text d-flex justify-content-center my-5"><%= t("users.edit.title") %></h1>

<div id="flash-message" class="mx-5">
  <%= render "shared/flash" %>
</div>

<h3 class="white-text d-flex justify-content-center my-5"><%= t("users.edit.form_title") %></h5>

<div class="mx-5">
  <% ["github", "mattermost", "notion", "note", "hatena_blog", "qiita", "zenn"].each do |website| %>
    <% link = @user.another_website_links.find_by(website: website) %>
      <div class="d-flex row mb-5">
        <%= form_with(model: [ @user, link || @user.another_website_links.build ], local: true, class: 'd-flex') do |form| %>
          <div class="form-floating flex-grow-1">
            <%= form.text_field :url, value: link&.url, class: "form-control", id: "#{website}_url", placeholder: "#{website.titleize}", aria: { label: website.titleize } %>
            <%= form.label :url, "#{website.titleize}", for: "#{website}_url" %>
            <%= form.hidden_field :website, value: website %>
          </div>
          <%= form.submit t("users.edit.form_submit"), class: "btn btn-outline-primary" %>
        <% end %>
        <div class="d-flex justify-content-center mt-2">
          <% if link %>
            <%= form_with(url: user_another_website_link_path(@user, link), method: :delete, class: 'd-flex') do |form| %>
              <%= form.submit t("users.edit.form_delete"), data: { turbo_confirm: t("users.edit.form_confirm_delete") }, class: "btn btn-outline-danger" %>
            <% end %>
          <% end %>
        </div>
      </div>
  <% end %>
</div>

<div class="d-flex justify-content-center my-5">
  <%= button_to t("users.edit.delete_account"), @user, method: :delete, data: { turbo_confirm: t("users.edit.confirm_delete") }, class: "btn btn-danger" %>
</div>

app/views/users/index.html.erb
<h1 class="white-text d-flex justify-content-center my-5"><%= t("users.index.title") %></h1>

<ul class="list-group mx-5">
  <% @users.each do |user| %>
    <li class="list-group-item d-flex justify-content-center align-items-center">
      <%= link_to user do %>
        <img src="<%= user.image %>" width="50" height="50" style="display: block; margin: auto;">
        <%= user.name %>
      <% end %>
        <%= render "follow_form", user: user %>
    </li>
  <% end %>
</ul>

<div class="d-flex justify-content-center my-5">
  <%= paginate @users, theme: "bootstrap-5" %>
</div>

app/views/users/show.html.erb
<div class="container my-5">
  <div class="card d-flex justify-content-center" style="text-align: center;">
    <img src="<%= @user.image %>" width="100" height="100" style="display: block; margin: auto;" class="mt-3">
    <div class="card-body">
      <h5><%= @user.name %></h5>

      <% if @user == current_user %>
        <div class="d-flex justify-content-center my-3">
          <button onclick="tweet(this)" data-text="テッテレー♪レベル<%= @user.level %>にあがった！" class="btn btn-dark">𝕏 Share</button>
        </div>
      <% end %>

      <%= render "follow_form", user: @user %>
      <%= render "rendering_modal" %>

      <h5 id="user_level">Level: <%= @user.level %></h5>
      <% @categories_progress.each_with_index do |(category, progress), index| %>
        <div class="progress" id="progress-bar-<%= index %>">
          <div class="progress-bar progress-bar-striped progress-bar-animated <%= progress_bar_color(index) %>" role="progressbar" style="width: <%= progress %>%;" aria-valuenow="<%= progress %>" aria-valuemin="0" aria-valuemax="100"><%= category %></div>
        </div>
      <% end %>

      <div class="d-flex justify-content-center" style="align-items: center;">
        <%= link_to image_tag("x.jpg", size: "25x25", class: "mx-3 mt-3"), "https://twitter.com/#{@user.nickname}", target: "_blank" %>
        <% @user.another_website_links.each do |link| %>
          <% if link.url.present? %>
            <%= link_to link.url, target: "_blank" do %>
              <%= image_tag("#{link.website}.jpg", size: "25x25", class: "mx-3 mt-3") %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <%= render "todo" %>
</div>