config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#top"
  get "/home/special_thanks", to: "home#special_thanks", as: "special_thanks"
  get "/home/terms", to: "home#terms", as: "terms"
  get "/home/privacy_policy", to: "home#privacy_policy", as: "privacy_policy"

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete "/sign_out", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
    resources :another_website_links, only: [:create, :update, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  resources :todos do
    resource :like, only: [:create, :destroy]
  end
end

app/views/shared/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="flash-message-design alert alert-dismissible fade show" role="alert">
    <%= flash[:notice] || flash[:alert] %>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="border-bottom thick-border">
    <ul class="nav justify-content-center">
      <li class="nav-item"><%= link_to "TOP", root_path, class: "nav-link white-text" %></li>
      <li class="nav-item"><%= link_to t("shared.footer.todo_form"), "https://docs.google.com/forms/d/e/1FAIpQLSeZA2zNaglw6g-CTd8-3JOg1mWNA6P-uxh0x0XqRoCVMTphMA/viewform", class: "nav-link white-text" %></li>
      <li class="nav-item"><%= link_to "SpecialThanks!!", special_thanks_path, class: "nav-link white-text" %></li>

      <li class="nav-item dropup">
        <a class="nav-link dropdown-toggle white-text" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Information</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="/home/terms"><%= t("shared.footer.terms_of_service") %></a></li>
            <li><a class="dropdown-item" href="/home/privacy_policy"><%= t("shared.footer.privacy_policy") %></a></li>
            <li><a class="dropdown-item" href="https://docs.google.com/forms/d/e/1FAIpQLSem-rlvwDvTYiSJXXkoF9SltbqDEdEjaoFLUpd4Ci1vOEN5vA/viewform"><%= t("shared.footer.contact_us") %></a></li>
            <li><a class="dropdown-item" href="https://runteq.jp/r/9_JVIuxH"><%= t("shared.footer.runteq") %></a></li>
          </ul>
      </li>

    </ul>
    <p class="text-center white-text">&copy; <%= Time.now.year %> CREDO QUEST</p>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarTogglerDemo01">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? && current_user %>
          <li class="nav-item">
            <%= button_to t("shared.header.user"), user_path(current_user), method: :get, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t("shared.header.todos_index"), todos_path, method: :get, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t("shared.header.users_index"), users_path, method: :get, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t("shared.header.edit"), edit_user_path(current_user), method: :get, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t("shared.header.sign_out"), "/sign_out", method: :delete, data: { turbo_confirm: t("shared.header.confirm_sign_out") }, class: "nav-link active btn btn-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= button_to t("shared.header.sign_in"), "/auth/twitter2", method: :post, data: { turbo: false }, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t("shared.header.todos_index"), todos_path, method: :get, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t("shared.header.users_index"), users_path, method: :get, class: "nav-link active btn btn-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Information</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="/home/terms"><%= t("shared.footer.terms_of_service") %></a></li>
                <li><a class="dropdown-item" href="/home/privacy_policy"><%= t("shared.footer.privacy_policy") %></a></li>
                <li><a class="dropdown-item" href="https://docs.google.com/forms/d/e/1FAIpQLSem-rlvwDvTYiSJXXkoF9SltbqDEdEjaoFLUpd4Ci1vOEN5vA/viewform"><%= t("shared.footer.contact_us") %></a></li>
                <li><a class="dropdown-item" href="https://runteq.jp/r/9_JVIuxH"><%= t("shared.footer.runteq") %></a></li>
              </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="d-flex d-flex align-items-center">
      <%= link_to image_tag("x.jpg", size: "25x25"), "https://twitter.com/CREDO_QUEST", class: "nav-link", style: "margin-right: 15px;", target: "_blank" %>
      <%= link_to image_tag("github.jpg", size: "25x25"),"https://github.com/furukawaeiichi/CREDO_QUEST", class: "nav-link", style: "margin-right: 15px;", target: "_blank" %>
      <%= audio_tag "/audios/bgm.mp3", controls: true, loop: true, data: { turbo_permanent: true }, id: "bgm", style: "width: 250px;" %>
    </div>
  </div>
</nav>