config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#top"
  get "/home/special_thanks", to: "home#special_thanks", as: "special_thanks"
  get "/home/terms", to: "home#terms", as: "terms"
  get "/home/privacy_policy", to: "home#privacy_policy", as: "privacy_policy"

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete "/sign_out", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
    resources :another_website_links, only: [:create, :update, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  resources :todos do
    resource :like, only: [:create, :destroy]
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  CATEGORIES = %w[BeOpen MoveFast GiveFirst GeekOut TakeOwnership].freeze

  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  scope :default_todos, -> { where(default: true) }
  scope :user_todos, -> { where(default: false) }

  after_save :update_user_level, if: :saved_change_to_checked?

  def self.ransackable_attributes(_auth_object = nil)
    ["category"]
  end

  def update_user_level
    if checked
      user.level += 1
    else
      user.level -= 1
    end
    user.save
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :destroy]
  before_action :authorize_todo, only: [:update]

  def index
    @q = Todo.user_todos.ransack(params[:q])
    @todos = @q.result.order(id: :desc).page(params[:page]).per(10)
    @todo = current_user.todos.new(default: false) if current_user
  end

  def show
  end

  def edit
  end

  def create
    @todo = current_user.todos.new(todo_params.merge(default: false))
    if @todo.save
      flash.now[:notice] = t("flash.todos.new.success")
    else
      flash.now[:error] = t("flash.todos.new.failure")
    end
  end

  def update
    if @todo.update(todo_params)
      flash.now[:notice] = t("flash.todos.update.success")
      update_user_level_and_categories_progress
    else
      flash.now[:error] = t("flash.todos.update.failure")
    end
  end

  def destroy
    if @todo.default == false && @todo.destroy
      flash.now[:notice] = t("flash.todos.destroy.success")
    else
      flash.now[:error] = t("flash.todos.destroy.failure")
    end
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def authorize_todo
    return unless current_user.nil? || @todo.user != current_user

    flash[:alert] = t("flash.todos.authorize_todo.alert")
    redirect_to user_path(@todo.user)
  end

  def todo_params
    params.require(:todo).permit(:category, :description, :checked)
  end

  def update_user_level_and_categories_progress
    @todo.update_user_level
    @categories_progress = @todo.user.categories_progress
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= turbo_frame_tag "todo/form" do %>
  <%= form_with(model: todo) do |form| %>
    <% if todo.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(todo.errors.count, "error") %> <%= t("todos.index.error") %></h2>

        <ul>
          <% todo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mx-5">
      <div class="input-group">
        <div>
          <%= form.select :category, Todo::CATEGORIES, {}, { class: "form-select" } %>
        </div>
        <%= form.text_field :description, class: "form-control", placeholder: t("todos.index.placeholder"), aria: { label: "Description" }, required: true %>
        <%= form.button class: "btn btn-primary" do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <% if todo.persisted? %>
          <%= link_to todos_path, data: { turbo_frame: "todo_#{todo.id}" }, class: "btn btn-secondary" do %>
            <i class="bi bi-backspace"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/todos/_like_button.html.erb
<div id="like_button_for_todo_<%= todo.id %>">
  <% if current_user != todo.user %>
    <% liked_users_images = todo.liked_users.map { |user| image_tag(user.image, height: 50) }.join(' ') %>
    <% if current_user&.liked?(todo) %>
      <%= button_to todo_like_path(todo), method: :delete, class: "btn btn-primary", style: "height: 50px;", data: { bs_toggle: "tooltip", bs_placement: "top", bs_html: "true", bs_original_title: liked_users_images } do %>
        <i class="bi bi-star-fill" style="color: #ffc107"></i>
        <span><%= todo.likes.count %></span>
      <% end %>
    <% else %>
      <%= button_to todo_like_path(todo), method: :post, class: "btn btn-primary", style: "height: 50px;", data: { bs_toggle: "tooltip", bs_placement: "top", bs_html: "true", bs_original_title: liked_users_images } do %>
        <i class="bi bi-star"></i>
        <span><%= todo.likes.count %></span>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag "todo_#{todo.id}" do %>
  <div class="mx-5 my-5">
    <div class="input-group">
      <%= image_tag todo.user.image, width: 50, height: 50, style: 'display: block; margin: auto;' %>

      <div class="input-group-text">
        <% if todo.user == current_user %>
          <%= form_with(model: todo, method: :patch, local: true) do |form| %>
            <%= form.check_box :checked, class: "form-check-input", onchange: 'this.form.requestSubmit(); triggerPartyEffect(this);' %>
          <% end %>
        <% else %>
          <input class="form-check-input" type="checkbox" <%= 'checked' if todo.checked %> aria-label="Checkbox" disabled>
        <% end %>
      </div>

      <input type="text" class="form-control" value="<%= todo.category %>" readonly aria-label="Category">
      <input type="text" class="form-control" value="<%= todo.description %>" readonly aria-label="Description" style="width: 65%;">

      <%= render 'todos/like_button', todo: todo %>

      <% if todo.user == current_user %>
        <button onclick="tweet(this)" data-text="テッテレー♪<%= todo.category %>「<%= todo.description %>」<%= todo.checked ? 'をクリアしました！' : 'にチャレンジします！' %>" class="btn btn-dark" style="height:50px; width:45px">𝕏</button>
        <%= button_to edit_todo_path(todo), method: :get, class: "btn btn-secondary", style: "height: 50px;" do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= button_to todo, method: :delete, data: { turbo_confirm: t("todos.index.delete") }, class: "btn btn-danger", style: "height: 50px;" do %>
          <i class="bi bi-trash3"></i>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos", @todo %>

<%= turbo_stream.replace "todo/form", partial: "todos/form", locals: { todo: current_user.todos.new } %>

<%= turbo_stream.update "flash", partial: "shared/flash" %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@todo) %>

<%= turbo_stream.update "flash", partial: "shared/flash" %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag "todo_#{@todo.id}" do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<h1 class="white-text d-flex justify-content-center my-5"><%= t("todos.index.title") %></h1>

<div class="d-flex justify-content-center">
  <div class="d-flex flex-column mx-3 text-center">
    <%= image_tag "dragon.jpg", size: "150x150", class: "mt-2" %>
    <p class="white-text mt-2"><%= t("todos.index.character") %></p>
  </div>
  <div class="d-flex flex-column mx-3">
    <div class="p-3 rounded bg-light" style="border: 1px solid black;">
      <p class="m-2"><%= t("todos.index.serif_1") %></p>
      <p class="m-2"><%= t("todos.index.serif_2") %></p>
    </div>
    <div class="p-3 rounded bg-light mt-2" style="border: 1px solid black;">
      <p class="m-2"><i class="bi bi-star-fill" style="color: #ffc107"></i><%= t("todos.index.serif_3") %></p>
    </div>
  </div>
</div>

<%= turbo_frame_tag "todos/index" do %>

  <div class="d-flex justify-content-center my-5">
    <%= search_form_for @q, url: todos_path, method: :get, html: { class: "d-flex align-items-center" } do |f| %>
      <%= f.select :category_eq, Todo::CATEGORIES, {include_blank: t("todos.index.search")}, {class: "form-select"} %>
      <%= f.button class: "btn btn-primary mx-1" do %>
        <i class="bi bi-search"></i>
      <% end %>
    <% end %>
  </div>

  <div id="flash" class="mx-5 my-5">
    <%= render "shared/flash" %>
  </div>

  <% if current_user %>
    <%= render "form", todo: @todo %>
  <% end %>

  <div id="todos">
    <% @todos.each do |todo| %>
      <%= render todo %>
    <% end %>
  </div>

  <div class="d-flex justify-content-center my-5">
    <%= paginate @todos, theme: "bootstrap-5" %>
  </div>
<% end %>

app/views/todos/update.turbo_stream.erb
<turbo-stream action="replace" target="user_level">
  <template>
    <h5 id="user_level">Level: <%= @todo.user.level %></h5>
  </template>
</turbo-stream>

<% @categories_progress.each_with_index do |(category, progress), index| %>
  <turbo-stream action="replace" target="progress-bar-<%= index %>">
    <template>
      <div class="progress" id="progress-bar-<%= index %>">
        <div class="progress-bar progress-bar-striped progress-bar-animated <%= progress_bar_color(index) %>" role="progressbar" style="width: <%= progress %>%;" aria-valuenow="<%= progress %>" aria-valuemin="0" aria-valuemax="100"><%= category %></div>
      </div>
    </template>
  </turbo-stream>
<% end %>

<%= turbo_stream.replace "todo_#{ @todo.id }", partial: "todos/todo", locals: { todo: @todo } %>

<%= turbo_stream.update "flash", partial: "shared/flash" %>